import type { Booking } from '@/lib/types';
import { MOCK_PARTNERS } from './partners';

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'b-001',
    userId: 'user-001',
    partnerId: 'p-001',
    partner: MOCK_PARTNERS.find(p => p.id === 'p-001'),
    activity: 'mall',
    date: '2025-01-20',
    startTime: '14:00',
    duration: 2,
    totalAmount: 1760,
    status: 'confirmed',
    meetingPoint: 'Phoenix Marketcity, Kurla - Main Entrance',
  },
  {
    id: 'b-002',
    userId: 'user-001',
    partnerId: 'p-007',
    partner: MOCK_PARTNERS.find(p => p.id === 'p-007'),
    activity: 'coffee',
    date: '2025-01-18',
    startTime: '11:00',
    duration: 1,
    totalAmount: 825,
    status: 'pending',
    meetingPoint: 'Starbucks, MG Road',
  },
  {
    id: 'b-003',
    userId: 'user-001',
    partnerId: 'p-002',
    partner: MOCK_PARTNERS.find(p => p.id === 'p-002'),
    activity: 'movies',
    date: '2025-01-15',
    startTime: '19:00',
    duration: 3,
    totalAmount: 1980,
    status: 'active',
    meetingPoint: 'PVR Saket, Gate 2',
  },
  {
    id: 'b-004',
    userId: 'user-001',
    partnerId: 'p-003',
    partner: MOCK_PARTNERS.find(p => p.id === 'p-003'),
    activity: 'outdoor',
    date: '2025-01-10',
    startTime: '07:00',
    duration: 2,
    totalAmount: 1540,
    status: 'completed',
    meetingPoint: 'Cubbon Park, Bandstand',
  },
  {
    id: 'b-005',
    userId: 'user-001',
    partnerId: 'p-005',
    partner: MOCK_PARTNERS.find(p => p.id === 'p-005'),
    activity: 'coffee',
    date: '2025-01-05',
    startTime: '16:00',
    duration: 1,
    totalAmount: 605,
    status: 'cancelled',
    meetingPoint: 'Filter Coffee House, Mylapore',
    cancelReason: 'Partner was unavailable due to emergency',
  },
];

export function getUserBookings(): Booking[] {
  return MOCK_BOOKINGS;
}
