import type { Partner } from '@/lib/types';

export const MOCK_PARTNERS: Partner[] = [
  {
    id: 'p-001',
    name: 'Priya Mehta',
    age: 24,
    gender: 'Female',
    bio: 'Mumbai-based coffee enthusiast and shopping buddy! I know every hidden café in Bandra and the best deals at Phoenix Marketcity. Whether you need a shopping partner or just someone to chat with over cappuccino, I\'m your person. Fluent in Hindi, English, and Marathi.',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    rating: 4.9,
    reviewCount: 132,
    hourlyRate: 800,
    activities: ['coffee', 'mall'],
    location: 'Mumbai',
    coords: { lat: 19.0596, lng: 72.8295 },
    isVerified: true,
    isOnline: true,
    images: [
      'https://randomuser.me/api/portraits/women/44.jpg',
      'https://randomuser.me/api/portraits/women/46.jpg',
      'https://randomuser.me/api/portraits/women/65.jpg',
      'https://randomuser.me/api/portraits/women/68.jpg',
    ],
    badges: ['Super Host', 'Top Rated'],
    joinedDate: '2023-06',
  },
  {
    id: 'p-002',
    name: 'Arjun Desai',
    age: 27,
    gender: 'Male',
    bio: 'Delhi boy who loves exploring the city! From Connaught Place to Hauz Khas, I know the best spots. Movie buff who can discuss cinema for hours. Great for mall trips or catching the latest Bollywood release.',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    rating: 4.7,
    reviewCount: 89,
    hourlyRate: 600,
    activities: ['mall', 'movies', 'outdoor'],
    location: 'Delhi',
    coords: { lat: 28.6304, lng: 77.2177 },
    isVerified: true,
    isOnline: true,
    images: [
      'https://randomuser.me/api/portraits/men/32.jpg',
      'https://randomuser.me/api/portraits/men/34.jpg',
      'https://randomuser.me/api/portraits/men/36.jpg',
    ],
    badges: ['Verified'],
    joinedDate: '2023-09',
  },
  {
    id: 'p-003',
    name: 'Kavya Sharma',
    age: 22,
    gender: 'Female',
    bio: 'Bengaluru tech girl who balances coding with café hopping! I know every specialty coffee shop in Koramangala. Love outdoor walks at Cubbon Park and weekend mall runs at Orion.',
    avatar: 'https://randomuser.me/api/portraits/women/40.jpg',
    rating: 4.8,
    reviewCount: 67,
    hourlyRate: 700,
    activities: ['coffee', 'outdoor', 'mall'],
    location: 'Bengaluru',
    coords: { lat: 12.9344, lng: 77.6101 },
    isVerified: true,
    isOnline: false,
    images: [
      'https://randomuser.me/api/portraits/women/40.jpg',
      'https://randomuser.me/api/portraits/women/42.jpg',
      'https://randomuser.me/api/portraits/women/52.jpg',
      'https://randomuser.me/api/portraits/women/55.jpg',
      'https://randomuser.me/api/portraits/women/58.jpg',
    ],
    badges: ['Rising Star'],
    joinedDate: '2024-01',
  },
  {
    id: 'p-004',
    name: 'Rohan Patel',
    age: 26,
    gender: 'Male',
    bio: 'Pune\'s outdoor adventure specialist! Trekking, morning walks at Shaniwar Wada, or evening jogs by the Mula-Mutha river. Also up for movie nights at the latest PVR screens. Fitness enthusiast and great conversationalist.',
    avatar: 'https://randomuser.me/api/portraits/men/75.jpg',
    rating: 4.5,
    reviewCount: 45,
    hourlyRate: 500,
    activities: ['outdoor', 'movies'],
    location: 'Pune',
    coords: { lat: 18.5167, lng: 73.8563 },
    isVerified: false,
    isOnline: true,
    images: [
      'https://randomuser.me/api/portraits/men/75.jpg',
      'https://randomuser.me/api/portraits/men/76.jpg',
      'https://randomuser.me/api/portraits/men/78.jpg',
    ],
    badges: [],
    joinedDate: '2024-03',
  },
  {
    id: 'p-005',
    name: 'Ananya Iyer',
    age: 25,
    gender: 'Female',
    bio: 'Chennai\'s culture enthusiast! Love exploring malls in T. Nagar, catching Tamil and Hindi movies at Sathyam Cinemas, and sipping filter coffee at the best spots in Mylapore. Your perfect Chennai companion!',
    avatar: 'https://randomuser.me/api/portraits/women/28.jpg',
    rating: 4.6,
    reviewCount: 58,
    hourlyRate: 550,
    activities: ['mall', 'coffee', 'movies'],
    location: 'Chennai',
    coords: { lat: 13.0674, lng: 80.2376 },
    isVerified: true,
    isOnline: false,
    images: [
      'https://randomuser.me/api/portraits/women/28.jpg',
      'https://randomuser.me/api/portraits/women/30.jpg',
      'https://randomuser.me/api/portraits/women/60.jpg',
      'https://randomuser.me/api/portraits/women/62.jpg',
    ],
    badges: ['Verified'],
    joinedDate: '2023-11',
  },
  {
    id: 'p-006',
    name: 'Vikram Singh',
    age: 29,
    gender: 'Male',
    bio: 'Mumbai sports and outdoor guy! From Marine Drive walks to hiking in the Western Ghats, I love being active. Also enjoy catching movies at PVR Juhu and shopping at Linking Road. Energetic and always on time!',
    avatar: 'https://randomuser.me/api/portraits/men/22.jpg',
    rating: 4.3,
    reviewCount: 34,
    hourlyRate: 450,
    activities: ['outdoor', 'movies', 'mall'],
    location: 'Mumbai',
    coords: { lat: 19.1136, lng: 72.8697 },
    isVerified: false,
    isOnline: true,
    images: [
      'https://randomuser.me/api/portraits/men/22.jpg',
      'https://randomuser.me/api/portraits/men/24.jpg',
      'https://randomuser.me/api/portraits/men/26.jpg',
    ],
    badges: [],
    joinedDate: '2024-05',
  },
  {
    id: 'p-007',
    name: 'Meera Nair',
    age: 23,
    gender: 'Female',
    bio: 'Kochi girl with a passion for coffee conversations! Specializing in cozy café meetups and relaxed mall outings. I believe great company turns ordinary outings into memorable experiences. Fluent in Malayalam, Hindi, and English.',
    avatar: 'https://randomuser.me/api/portraits/women/18.jpg',
    rating: 4.9,
    reviewCount: 112,
    hourlyRate: 750,
    activities: ['coffee', 'mall'],
    location: 'Kochi',
    coords: { lat: 9.9685, lng: 76.2842 },
    isVerified: true,
    isOnline: true,
    images: [
      'https://randomuser.me/api/portraits/women/18.jpg',
      'https://randomuser.me/api/portraits/women/20.jpg',
      'https://randomuser.me/api/portraits/women/48.jpg',
      'https://randomuser.me/api/portraits/women/50.jpg',
    ],
    badges: ['Super Host', 'Top Rated'],
    joinedDate: '2023-03',
  },
  {
    id: 'p-008',
    name: 'Aditya Kumar',
    age: 28,
    gender: 'Male',
    bio: 'Hyderabad\'s movie maniac! I watch every Tollywood and Bollywood release on day one. Great company for film discussions and mall hopping at Inorbit. Also enjoy early morning walks at Hussain Sagar Lake.',
    avatar: 'https://randomuser.me/api/portraits/men/18.jpg',
    rating: 4.4,
    reviewCount: 41,
    hourlyRate: 500,
    activities: ['movies', 'mall', 'outdoor'],
    location: 'Hyderabad',
    coords: { lat: 17.4065, lng: 78.4772 },
    isVerified: true,
    isOnline: false,
    images: [
      'https://randomuser.me/api/portraits/men/18.jpg',
      'https://randomuser.me/api/portraits/men/20.jpg',
      'https://randomuser.me/api/portraits/men/28.jpg',
    ],
    badges: ['Verified'],
    joinedDate: '2024-02',
  },
  {
    id: 'p-009',
    name: 'Sneha Reddy',
    age: 21,
    gender: 'Female',
    bio: 'Bengaluru\'s youngest companion! College student who loves exploring the city. From Brigade Road shopping to Indiranagar café crawls, I bring energy and fun to every outing. Budget-friendly and always smiling!',
    avatar: 'https://randomuser.me/api/portraits/women/24.jpg',
    rating: 4.7,
    reviewCount: 76,
    hourlyRate: 400,
    activities: ['coffee', 'mall', 'outdoor'],
    location: 'Bengaluru',
    coords: { lat: 12.9719, lng: 77.5937 },
    isVerified: true,
    isOnline: true,
    images: [
      'https://randomuser.me/api/portraits/women/24.jpg',
      'https://randomuser.me/api/portraits/women/26.jpg',
      'https://randomuser.me/api/portraits/women/56.jpg',
      'https://randomuser.me/api/portraits/women/58.jpg',
    ],
    badges: ['Rising Star', 'Verified'],
    joinedDate: '2024-04',
  },
  {
    id: 'p-010',
    name: 'Karan Malhotra',
    age: 30,
    gender: 'Male',
    bio: 'Delhi\'s premium companion for upscale experiences! Specializing in luxury mall visits at Select Citywalk and fine coffee tastings. Professional, well-dressed, and excellent conversation partner. Perfect for business social events.',
    avatar: 'https://randomuser.me/api/portraits/men/14.jpg',
    rating: 4.8,
    reviewCount: 95,
    hourlyRate: 1500,
    activities: ['mall', 'coffee'],
    location: 'Delhi',
    coords: { lat: 28.5800, lng: 77.1950 },
    isVerified: true,
    isOnline: false,
    images: [
      'https://randomuser.me/api/portraits/men/14.jpg',
      'https://randomuser.me/api/portraits/men/16.jpg',
      'https://randomuser.me/api/portraits/men/30.jpg',
      'https://randomuser.me/api/portraits/men/33.jpg',
    ],
    badges: ['Premium', 'Super Host'],
    joinedDate: '2023-01',
  },
  {
    id: 'p-011',
    name: 'Divya Gupta',
    age: 26,
    gender: 'Female',
    bio: 'Jaipur\'s outdoor explorer! Love heritage walks through the Pink City, sunset visits to Nahargarh, and shopping at Johari Bazaar. Also a movie buff who never misses a Friday release. Warm and welcoming personality!',
    avatar: 'https://randomuser.me/api/portraits/women/36.jpg',
    rating: 4.6,
    reviewCount: 52,
    hourlyRate: 600,
    activities: ['outdoor', 'mall', 'movies'],
    location: 'Jaipur',
    coords: { lat: 26.9155, lng: 75.8190 },
    isVerified: false,
    isOnline: true,
    images: [
      'https://randomuser.me/api/portraits/women/36.jpg',
      'https://randomuser.me/api/portraits/women/38.jpg',
      'https://randomuser.me/api/portraits/women/64.jpg',
    ],
    badges: [],
    joinedDate: '2024-06',
  },
  {
    id: 'p-012',
    name: 'Nikhil Joshi',
    age: 25,
    gender: 'Male',
    bio: 'Pune café culture expert! I\'ve visited over 100 cafés in Pune and maintain a blog about them. Great for coffee dates and casual mall outings. Friendly, punctual, and always bring good vibes. Also enjoy outdoor activities around Lavasa.',
    avatar: 'https://randomuser.me/api/portraits/men/10.jpg',
    rating: 4.2,
    reviewCount: 28,
    hourlyRate: 350,
    activities: ['coffee', 'mall', 'outdoor'],
    location: 'Pune',
    coords: { lat: 18.5083, lng: 73.8250 },
    isVerified: false,
    isOnline: false,
    images: [
      'https://randomuser.me/api/portraits/men/10.jpg',
      'https://randomuser.me/api/portraits/men/12.jpg',
      'https://randomuser.me/api/portraits/men/34.jpg',
    ],
    badges: [],
    joinedDate: '2024-07',
  },
];

export function getPartners(): Partner[] {
  return MOCK_PARTNERS;
}

export function getPartnerById(id: string): Partner | undefined {
  return MOCK_PARTNERS.find(p => p.id === id);
}
